[package]
name = "bc_signals_train"
version = "0.1.0"
edition = "2024"

[dependencies]
bc_utils_lg ={ path = "../bc_utils_lg" }
bc_utils = {path = "../bc_utils"}

[dev-dependencies]
bc_test_kit = {path = "../bc_test_kit"}

criterion = {version = "0.8", features = ["html_reports"]}
pretty_assertions = "1"

[[bench]]
name = "mm"
path = "benches/mm.rs"
harness = false