[package]
name = "bc_signals_train"
version = "0.1.0"
edition = "2024"

[dependencies]
bc_utils_lg ={ git = "https://github.com/rXZD5cFumBJnx56wcclz/bc_utils_lg.git", branch = "main"}
bc_utils = {git = "https://github.com/rXZD5cFumBJnx56wcclz/bc_utils.git", branch = "main"}

dyn-clone = "1"

[dev-dependencies]
bc_test_kit = {git = "https://github.com/rXZD5cFumBJnx56wcclz/bc_test_kit.git", branch = "main"}

criterion = {version = "0.8", features = ["html_reports"]}
pretty_assertions = "1"

[[bench]]
name = "mm"
path = "benches/mm.rs"
harness = false